import { memo, useState } from "react";
import fairyImg from "../gallery 3d models/character-fairy.png";
import astronautImg from "../gallery 3d models/character-astronaut.png";
import superheroImg from "../gallery 3d models/character-superhero.png";
import elsaImg from "../gallery 3d models/elsabg.png";
import bossBabyImg from "../gallery 3d models/bossbaby-blue.png";
import onePieceImg from "../gallery 3d models/one-piece-blue.png";
import snowWhiteImg from "../gallery 3d models/snowwhite-blue.png";
import moanaImg from "../gallery 3d models/moana-blue.png";

const galleryImages = [
  { id: 1, src: onePieceImg, title: "Adventure Hero" },
  { id: 2, src: snowWhiteImg, title: "Classic Princess" },
  { id: 3, src: superheroImg, title: "Superhero" },
  { id: 4, src: elsaImg, title: "Ice Princess" },
  { id: 5, src: astronautImg, title: "Astronaut" },
  { id: 6, src: fairyImg, title: "Fairy" },
  { id: 7, src: bossBabyImg, title: "Business Baby" },
  { id: 8, src: moanaImg, title: "Island Princess" },
];

const FEATURED_COUNT = 4;

const Gallery = memo(() => {
  const [showAll, setShowAll] = useState(false);
  const hasMoreThanFeatured = galleryImages.length > FEATURED_COUNT;
  const visibleImages = showAll || !hasMoreThanFeatured
    ? galleryImages
    : galleryImages.slice(0, FEATURED_COUNT);

  return (
    <section className="py-32 px-6">
      <div className="max-w-7xl mx-auto space-y-16">
        <div className="flex flex-col md:flex-row justify-between items-end gap-8">
          <div className="space-y-4">
            <h2 className="text-5xl md:text-6xl font-bold tracking-tighter uppercase">
              Community <br /> Showcase
            </h2>
            <p className="text-white/40 max-w-md">
              Explore a collection of high-fidelity assets generated by our users using the 3DGENI neural
              engine.
            </p>
          </div>
          {hasMoreThanFeatured && (
            <button
              type="button"
              onClick={() => setShowAll((prev) => !prev)}
              className="px-8 py-4 rounded-full glass hover:bg-white/10 transition-all text-[11px] uppercase tracking-widest"
            >
              {showAll ? "View Featured" : "View All Assets"}
            </button>
          )}
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {visibleImages.map((asset) => (
            <div
              key={asset.id}
              className="group relative aspect-square rounded-3xl overflow-hidden glass transform transition-transform duration-500 hover:-translate-y-2"
            >
              <img
                src={asset.src}
                alt={asset.title}
                className="w-full h-full object-cover opacity-70 group-hover:opacity-100 group-hover:scale-110 transition-all duration-700"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
              <div className="absolute bottom-6 left-6 right-6 translate-y-4 group-hover:translate-y-0 opacity-0 group-hover:opacity-100 transition-all duration-500">
                <p className="text-[10px] uppercase tracking-widest text-white/60 mb-1">Character</p>
                <p className="text-lg font-bold uppercase">{asset.title}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
});

Gallery.displayName = 'Gallery';

export default Gallery;
